### ISSUE TITLE
Ellipsis Typography

### ISSUE THREAD

**Issue by Frizlab** [rrthomas/hpmor#111]
It was my understanding that ellipsis should have a space after them in English. I am mistaken?

E.g.
> “What lay ahead of her… would be no easier, certainly, and might well be harder.”

instead of
> “What lay ahead of her…would be no easier, certainly, and might well be harder.”

**Comment by rrthomas** [comment]
In short, no, there shouldn't be *a* space; rather, *some* space before and after. LaTeX takes care of the spacing. Thanks for asking!

**Comment by natewind** [comment]
> In short, no, there shouldn't be _a_ space; rather, _some_ space before and after. LaTeX takes care of the spacing. Thanks for asking!

Maybe LaTeX does, but EPUB doesn’t. And the current converter doesn’t insert any kind of space.

Also, I don’t know anything about the space before (sonds like a kerning issue TBH), but it definitely shouldn’t be as big as the space after. Ellipsis sticks to the previous word, just like a period, a comma, a (semi)colon or a question/exclamation mark.

**Comment by natewind** [comment]
> I follow the _Chicago Manual of Style_, whose advice is reproduced here: https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Punctuation/faq0133.html

Damn those examples look weird... That’s why I cherry-pick style guidelines.

But ok, I guess I’ll just have to search and replace in my own copy so that it looks normal.

**Comment by entorb** [comment]
If the problem only effects the ebook, we could perform the search and replace in the ebook script. On the other hand, if LaTeX handles the spacing around the ellipsis, it would not hurt to apply the rules directly to the source files. If we agree on a set of rules, I am happy to apply them in the coding.

**Comment by entorb** [comment]
So, who would like to propose a rule set for spacing around ellipsis in the ebook? (which are html internally)

**Comment by natewind** [comment]
I propose adding a space after it, unless it’s the beginning of a sentence, in which case add a space before.

**Comment by entorb** [comment]
So rules like

foo… bar
foo. …Bar

How about opening and closing "?
"… foo…" according to above rules.
I think I would prefer
"…foo…"

How about end of sentence and before comma?
I suggest
foo…!
foo…,
etc

Feel free to correct me and come up with more rules ;-)

**Comment by natewind** [comment]
Stick to the alphanumeric character on the left if any, otherwise on the right?

> foo…,

Personally, I agree with [this](https://english.stackexchange.com/a/43629): an ellipsis makes a comma redundant.

> foo…!

Well, we could copy this elegant punctuation rule from Russian:

* foo?..
* foo!..

But I doubt many people would agree with me on this x)

**Comment by entorb** [comment]
Hi @rrthomas: would it harm to perform such replacement rules directly on the LaTeX files? If not, I would prefer using the check-chapter script to enforce it centrally instead of only in (and at each run of) the ebook creation scripts.

**Comment by rrthomas** [comment]
@entorb I'd rather not change the LaTeX files as that will change the spacing LaTeX produces. As you probably know, it's rather like HTML: any number of spaces equals one space in its effect, so changing between 0 and 1 space changes the result (usually…of course nothing in TeX-world is ever quite *that* simple).

**Comment by entorb** [comment]
Please review and commend the PR.

Bye the way, should we also harmonize the spaces around the em dash "—" in the ebook version?

Do you have proposals for it?

**Comment by rrthomas** [comment]
@entorb, I'm happy with the PR; feel free to merge it.

Harmonizing space around em dash is also a good idea.

I should say: I think we've looked at these matters before, so the LaTeX *should* be correct by now, but I certainly don't rule out errors in particular cases. I don't know whether any of the patterns in your fix functions actually detect errors in the LaTeX, that is, cases that should not be present in the LaTeX sources and which therefore should not show up in the ePUB conversion?

**Comment by entorb** [comment]
at @natewind , @Frizlab here you can check the changes in the pre-release version
https://github.com/rrthomas/hpmor/releases/tag/WorkInProgress

**Comment by natewind** [comment]
> at @natewind , @Frizlab here you can check the changes in the pre-release version
> https://github.com/rrthomas/hpmor/releases/tag/WorkInProgress

Thanks!

**Comment by Frizlab** [comment]
LGtM in the `epub`. Thanks!

**Comment by rrthomas** [comment]
@entorb, would you like to make a release? I'm not sure if you've done it before, so get in touch if you need help.

**Comment by entorb** [comment]
ok, done via the github release action I composed some time ago ;-)
https://github.com/rrthomas/hpmor/releases/tag/v1.2.9

**Comment by rrthomas** [comment]
Ah yes, great!
