### ISSUE TITLE
Consider adding the FB2 target

### ISSUE THREAD

**Issue by natewind** [rrthomas/hpmor#115]
It’s nice because it has purely semantic markup and gives the reader full control over formatting.

**Comment by entorb** [comment]
Here you go:
https://github.com/rrthomas/hpmor/releases/download/WorkInProgress/hpmor.fp2
Please check if the file is as expected.

**Comment by natewind** [comment]
No, it looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
<description>
	<title-info>
		<lang>en</lang>
		<author>
			<first-name>Eliezer</first-name>
			<last-name>Yudkowsky</last-name>
		</author>
		<book-title>Harry Potter and the Methods of Rationality</book-title>
	</title-info>
	<!--Possibly other metadata-->
</description>
<body>
	<title>
		<p>Eliezer Yudkowsky</p>
		<p>Harry Potter and the Methods of Rationality</p>
	</title>
	<section>
		<title>
			<p>Chapter 1: A Day of Very Low Probability</p>
		</title>
		<empty-line/>
		<epigraph>
			<p>Beneath the moonlight glints a tiny fragment of silver, a fraction of a line...</p>
			<p>(black robes, falling)</p>
			<p>...blood spills out in litres, and someone screams a word.</p>
		</epigraph>
		<empty-line/>
		<p>Every inch of wall space is covered by a bookcase...</p>
	</section>
	<section>
		<title>
			<p>Chapter 2: Title</p>
		</title>
		<empty-line/>
		<p>Example text, <emphasis>italic text</emphasis>, <strong>bold text</strong></p>
	</section>
</body>
</FictionBook>
```

(Also, it’s fb2, not fp2)

**Comment by entorb** [comment]
Ups, sorry for the typo. please check https://github.com/rrthomas/hpmor/releases/download/WorkInProgress/hpmor.fb2

**Comment by natewind** [comment]
I’s mostly correct, but there’s some text missing because it ended up outside the `<p>` tags.

E. g.

```xml
<title><p>1. A Day of Very Low Probability</p></title>“Beneath the moonlight...
```

And at the end:

```xml
“I <emphasis>do</emphasis> choose this, now.”</p>Upon my life and magic...
```
```xml
...live long, and prosper”</p><empty-line />“EXPECTO PATRONUM!”
```

**Comment by entorb** [comment]
Hope this will be fixed as a by-product of https://github.com/rrthomas/hpmor/pull/118 
(Haven't verified yet, but the German edition (where I already use the V2 of the ebook scripts) looks promising: https://github.com/entorb/hpmor-de/releases/download/WorkInProgress/hpmor.html)

**Comment by entorb** [comment]
please check the new file at
https://github.com/rrthomas/hpmor/releases/download/WorkInProgress/hpmor.fb2

**Comment by natewind** [comment]
The same problem persists :(

**Comment by entorb** [comment]
Damn! Will try to fix tomorrow.

**Comment by entorb** [comment]
Found it: I forgot to update one path for the new ebook version in the workflow that uploads the files to the release. Now the new file is included in the WorkInProgress release: https://github.com/rrthomas/hpmor/releases/download/WorkInProgress/hpmor.fb2

**Comment by natewind** [comment]
Yep, it’s fixed!

**Comment by entorb** [comment]
Finally! ;-)
