### ISSUE TITLE
Strange wording in chapter 46

### ISSUE THREAD

**Issue by dcorderoch** [rrthomas/hpmor#121]
In line 224 of `chapters/hpmor-chapter-046.tex`

this phrase:

```
... “Thank you, Minerva. You are a good woman and true.”
```

(`...` for brevity)

it seems like there is a missing word after true, maybe `friend`?

but I'm not sure if this is a British English phrase I'm not familiar with

**Comment by rrthomas** [comment]
This is a British English phrase (or template): "a good X and true [X]". Maybe it would be good to add a comment "% (sic)" here to avoid this being re-raised by future readers who check the source? I would happily merge such a PR!
