### ISSUE TITLE
Fails to build as of 9ef84f7

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/hpmor#123]
```
contour: Using 120 copies for `Harry James Potter-Evans-Verres and the Methods 
of Rationality' on input line 69.

! LaTeX Error: Part 'remark' is undefined..

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.69 \makebookcover
                   
? 
```

I suspect this may be due to changes in TeXLive.

**Comment by entorb** [comment]
The auto build via workflow uses Ubuntu 22.04 and there it worked yesterday. Maybe newer Texlive 
introduces new problems...

**Comment by rrthomas** [comment]
I'm using TeXLive from Ubuntu 22.04…

**Comment by rrthomas** [comment]
OK, the problem is with the dust jackets, and the GitHub workflow doesn't make those.

**Comment by rrthomas** [comment]
Yup, the `bookcover` document class seems to have changed incompatibly. Unfortunately, I can't find any migration guide or even version history, so I'll have to work it out!

**Comment by rrthomas** [comment]
Fix incoming. The odd thing is that the current version of `bookcover` seems to have code in it specifically to support the old syntax; but it's no longer documented, and I guess it no longer works…

**Comment by rrthomas** [comment]
Fixed.

**Comment by entorb** [comment]
Thanks for fixing, will copy to my German repo ;-)

In parallel I created a workflow for creation of new releases:
https://github.com/rrthomas/hpmor/actions/workflows/create-release.yml

**Comment by rrthomas** [comment]
Thanks for the release workflow; I think I would have chosen 1.3 to celebrate the addition of FB2, but it really doesn't matter as long as we have a different number each time (could just be consecutive integers in future to be honest, then that could be automated too).
