### ISSUE TITLE
Possible improvement

### ISSUE THREAD

**Issue by dcorderoch** [rrthomas/hpmor#134]
in chapter 97, there is a "thought bubble"/`\emph{} block`, where Harry thinks (as if talking to Lucius) "... sent the troll after Granger..." (line 154 in the .tex file)

I thought he should say "Hermione", rather than "Granger", because he's not actually speaking as opposed to when he was talking to Draco in chapter 23, when he said "... then Hermione Granger doesn't make sense... I could go to Granger and ask..." (line 219 of the .tex file), saying "Granger" then, and to me it kind of makes sense, because he is "acting" there (though the more I think about it, it "sounds" strange to me)

I wanted to ask instead of adding a PR directly, because I thought I might be missing something? like context from a later chapter, or if it's simply more common to refer to people (who are not part of a conversation) by their surnames, rather than their first names in British English? I must admit I usually hear people using given names in tv/movies, and I don't read as much literature, so it sounds a bit off to me, but I'm uncertain if it could be an improvement to use "Hermione", or if it's just a difference of spoken and written English, or even if it's a British English thing

**Comment by rrthomas** [comment]
I think the use of the surname is correct here, as although Harry is thinking rather than speaking, he's imagining what he would say, and if he were speaking, the use of Hermione's surname would be what you'd expect of Harry speaking to Lucius.
