### ISSUE TITLE
Language in EPUB metadata is set to "de" (German)

### ISSUE THREAD

**Issue by arjunsatarkar** [rrthomas/hpmor#138]
Reproduce: import to Calibre, see it's tagged as German. Also tried with https://www.metadata2go.com/ which returns the same results.

Expected behaviour/fix: should be set to English.

Thanks for this project!

**Comment by entorb** [comment]
Good catch, was a copy&paste problem. Fixed in https://github.com/rrthomas/hpmor/commit/494440fee2cc058111a1572c2cb0a346328ff822 to en-US

**Comment by rrthomas** [comment]
Thanks, both; I have made a new release.

**Comment by arjunsatarkar** [comment]
FYI, while a new tag was pushed, there doesn't seem to be a release built from it at https://github.com/rrthomas/hpmor/releases.
