### ISSUE TITLE
Missing sections of text in 1.2.2

### ISSUE THREAD

**Issue by Akiiino** [rrthomas/hpmor#141]
In the latest release (1.2.2) there are whole missing sections of text (at least) in the `.epub` and `.mobi` versions. Specifically, in book 1, chapter 13, the note that is supposed to say

> HA! HA HA HA HA HA!
> HA HA HA HA HA HA!
> HA! HA! HA! HA! HA! HA!
> DUMBLEDORE DOES NOT CONTROL THE GAME
> BAD GUESS
> VERY BAD GUESS
> -20 POINTS
> AND YOU ARE STILL WEARING PYJAMAS
> IT IS YOUR FOURTH MOVE
> AND YOU ARE STILL WEARING PYJAMAS
> PYJAMA PENALTY: -2 POINTS
> CURRENT POINTS: 75

instead only says

> PYJAMA PENALTY: -2 POINTS
> CURRENT POINTS: 75

And more notes throughout the chapter are missing significant parts of their content.

This seems to be a recent regression, as release 1.2 does not seem to be suffering from this issue.

**Comment by entorb** [comment]
Thanks for reporting this bug. I will look into it.
