### ISSUE TITLE
Visual asymmetry in horizontal rule under chapterOpeningQuote

### ISSUE THREAD

**Issue by LunarTulip** [rrthomas/hpmor#143]
Chapters with opening quotes currently look like this, in the PDFs:

![image](https://user-images.githubusercontent.com/12496016/236677969-73beb9c9-f8aa-4cb0-8bb1-96b50d7d3a0c.png)

For the most part, this layout holds together pretty well. However, there's one specific fashion in which it seems clearly aesthetically suboptimal: the horizontal rule between the opening quote and the first paragraph. Or, more particularly: the fact that said horizontal rule has much less empty vertical space above it than below it, giving it an awkward sort of asymmetry.

To fix the issue, I suggest adding additional empty space above the horizontal rule, to render it symmetric. (Or, if there's some reason this was considered and rejected, I'd be interested to know what the reason is, for purposes of figuring out a better alternative.)

**Comment by entorb** [comment]
Thanks for pointing this out. I suggest removal of the line (which I have introduced when I added the chapterOpeningQuote env). Would that make sense for you?

**Comment by LunarTulip** [comment]
That makes sense, yeah. Possibly accompanied by slightly-thicker margins, in order to offer a clear visual indication that the opening quote should be taken as an epigraph rather than as a normal-text-block-with-a-mysteriously-large-space-underneath?

**Comment by entorb** [comment]
Please check the new WIP release in approx 20 minutes from now:
https://github.com/rrthomas/hpmor/releases/tag/WorkInProgress

**Comment by LunarTulip** [comment]
Checked it; it looks good!

**Comment by entorb** [comment]
Great. Will close this issue now, a new release should be created once the other footnote issue is fixed too.
