### ISSUE TITLE
Processing fails when trying to upload the epub to google books

### ISSUE THREAD

**Issue by sheepdestroyer** [rrthomas/hpmor#148]
Processing fails when trying to upload the epub to google books:
![image](https://github.com/rrthomas/hpmor/assets/1377479/b42f94bf-733b-49d5-9fe9-6747f9a1ed98)

**Comment by entorb** [comment]
Can reproduce, same for the .mobi file. Strange, since other reader seems not of have an issue with the files.

ebooks are generated by calibre's tool ebook-convert, see https://github.com/rrthomas/hpmor/blob/main/scripts/ebook/7.sh#L20

Sorry, but currently I have no idea how to fix this.

**Comment by sheepdestroyer** [comment]
Maybe that won't be much help but,
converting from epub to epub  using calibre 6.22 gave me a file that was accepted by Google.

**Comment by entorb** [comment]
The currently used ubuntu in the GitHub Action build process is Ubuntu 22.04.2 LTS and ships with:
`ebook-convert (calibre 5.37.0)`

Will give a Ubuntu 23.04 a try.

**Comment by entorb** [comment]
Same problem, when creating the ebook via Ubuntu 23.04 that ships with `ebook-convert (calibre 6.11.0)`

**Comment by entorb** [comment]
By the way, an experiment in my German hpmor repo turned out, that there seem to be few runner instances in GitHub Actions for Ubuntu 23.04 available, so better stick to the LTS versions.

**Comment by rrthomas** [comment]
At the risk of stating the obvious, it should be possible to install a more recent calibre from Homebrew (which is included in the Ubuntu GitHub runners).

**Comment by lord-ne** [comment]
Even manually fixing all the epubcheck errors still doesn't give a file that's accepted by Google Play Books

**Comment by entorb** [comment]
Hi, I did some minor HTML cleanup to satisfy https://validator.w3.org and removed the (not needed) images. Looks like that finally fixed this issue for the epub import, see [latest .epub](https://github.com/rrthomas/hpmor/releases/download/WorkInProgress/hpmor.epub)
(.mobi seems to be rejected by Google books, but I don't care for the moment)

**Comment by rrthomas** [comment]
Well done @entorb!
