### ISSUE TITLE
PDF: The triple star sign is borked

### ISSUE THREAD

**Issue by mmavova** [rrthomas/hpmor#149]
When I open the pdf, the triple-star sign is borked. See, for example, the top of page 4. On the left the rightmost star is smaller then it should be. On the right the leftmost star is smaller.

**Comment by rrthomas** [comment]
This seems to be deliberate:

```
% Three “magic stars” decoration
\def\Stars{{\large\Star\kern-.6ex\lower1.3ex\hbox{\large\Star}\kern-.1ex\raise.2ex\hbox{\tiny\Star}\spacefactor1000}}
```

Note the `\large` and the `\tiny`.

**Comment by rrthomas** [comment]
(It's always been this way, I checked.)
