### ISSUE TITLE
"didn't used to" -> "did not use to"

### ISSUE THREAD

**Issue by mmavova** [rrthomas/hpmor#150]
There are many instances of "didn't used to ..." in HPMOR or similar. 

For example, page 373:

"What kind of Charms did students used to cast in their first year at
Hogwarts" 

page 436: "That didn’t used to happen in the ancestral environment"
And so on.

The correct grammar when "used to" is used with the auxiliary verb "did", then it should be "use to". 
See, for example, https://www.thesaurus.com/e/grammar/use-to-or-used-to/

**Comment by rjl20** [comment]
"Didn't use to" is technically correct grammar, and "didn't used to" is technically wrong, but this is one of those things where so many people use the incorrect version that it's probably a lost cause for the prescriptivists.

"Used to" : "Didn't use to" :: "Started to" : "Didn't start to"
"Used to" : "Didn't used to" :: "Started to" : "Didn't started to"

So... obscure, but correct. I have no opinion on which to use.

**Comment by rrthomas** [comment]
Some considerations:

1. It's idiomatic English.
2. It probably nonetheless shouldn't occur outside direct or (possibly) indirect speech.
3. Even a pedantic speaker might use it for effect or humour (at least, speaking as a pedant who attempts humour, I do!).
4. I'm not sure about Hermione. ("I didn't used to understand", chapter 122.)

So, I'd certainly consider individual changes that are motivated, but not a blanket switch.

**Comment by rrthomas** [comment]
Closing. As I said above, I'd consider specific motivated changes!
