### ISSUE TITLE
Some typos and other minor issues

### ISSUE THREAD

**Issue by mmavova** [rrthomas/hpmor#152]
Here is the list of typos/issues I noticed during a reread (I read the pdf). 

Obvious typos/bugs:

1. [x] page 1450 "Has the headmaster has told you" -> "Has the headmaster told you" 
2. [x] page 1418 "an glowing orb" -> "a glowing orb"
3. The opening quotation mark does not render properly for me in many places: page 1555 twice ('dark side' becomes �dark side’), page 1556, page 1881(�phœnix’s price’, �phœnix’s fate’, and
�phœnix’s egg’), page 1883, page 102. I am not sure if it is the same in other book formats. 
4. [x] chapter 85:  stick-your-neck-out-and-make-a-prediction-or-stop-pretending-to-believe-in-your- theory  should not have the space in there: "stick-your-neck-out-and-make-a-prediction-or-stop-pretending-to-believe-in-your-theory".
5. [x] page 1790 "Tell you me you will wait" -> "Tell me you will wait"

Not sure/debatable:
1. Omake files on fanfiction.net had titles, and some are missing in the pdf. 
2. [x] The last page on fanfiction.net and in the pdf are different. "EXPECTO PATRONUM!" is not a part of the text on fanfiction.net, but rather in author's notes. Looking at LaTeX source, it looks like that was not the original intention, but a glitch with the compilation. The glitch does not show up on hpmor.com.
3. [x] page 1800: "Into the hand of the Albus Dumbledore" -> "Into the hand of Albus Dumbledore".
4. [x] On page 1708 (chapter 104) you need something like a "\noskip" to suppress the extra space on the first "And" in 

> And\\
> And\\
> And Professor Quirrell had known a password

**Comment by rrthomas** [comment]
Thanks for this, I'll look at it soon!

**Comment by rrthomas** [comment]
@mmavova, I have gone through and fixed all but one of these. Please could you give a bit more detail on this one:

* Omake files on fanfiction.net had titles, and some are missing in the pdf.
