### ISSUE TITLE
Omake titles missing in the pdf

### ISSUE THREAD

**Issue by mmavova** [rrthomas/hpmor#153]
1. In the pdf: "Omake Files I". On fanfiction.net:  `OMAKE FILES #1: 72 Hours to Victory`. The title is present in https://hpmor.com/chapter/11, but is missing in the pdf.
2. Same for Omake files 2, it should say `OMAKE FILES #2: I Ain't Afraid of Dark Lords` in the pdf.
3. Omake 3 should be `OMAKE FILES #3: Alternate Endings of 'Self-Awareness`'.

**Comment by rrthomas** [comment]
Many thanks for this!
