### ISSUE TITLE
Chapter 38 in wrong section

### ISSUE THREAD

**Issue by LiamGoddard** [rrthomas/hpmor#154]
Chapter 38 (The Cardinal Sin) should be part of Book 3, not Book 2, but it's currently in Book 2 in the Table of Contents, and the "Part III" header is after it instead of before it.

**Comment by entorb** [comment]
@rrthomas : do you know why in the single volume edition the chapter is in different part than in the complete edition? Which is right?

**Comment by entorb** [comment]
Found it, was my fault.
see https://github.com/rrthomas/hpmor/issues/34 and https://www.reddit.com/r/HPMOR/comments/2z116j/comment/cpeqcdh/
