### ISSUE TITLE
Space around quotation mark misplaced

### ISSUE THREAD

**Issue by b-jonas0** [rrthomas/hpmor#173]
In chapter 101, page 1653, before ‘What Muggles have learned’, the space should be before the opening quotation mark, not after.

**Comment by entorb** [comment]
thanks! Fixed in 101 and 107, and added this rule to the check chapter script. Not created a new release yet. Will be published to [WorkInProgress](https://github.com/rrthomas/hpmor/releases/tag/WorkInProgress) in a few minutes.
