### ISSUE TITLE
Single quotes rendered incorrectly in handwriting font

### ISSUE THREAD

**Issue by b-jonas0** [rrthomas/hpmor#174]
Chapter 119, page 1881, Dumbledore's first letter, before the passwords, the opening single quotation marks don't show up properly and a large rectangle is rendered in their place.  

(To be honest I don't like this new font for the handwritten letters.)

**Comment by entorb** [comment]
I cannot reproduce this. Checked the [PDF of the latest release](https://github.com/rrthomas/hpmor/releases/download/v1.2.14/hpmor.pdf) in Firefox, looks good to me:
![1881](https://github.com/user-attachments/assets/4cadeea3-c28a-411f-ac4a-d2281cc2d735)

**Comment by moiSentineL** [comment]
> Indeed, I was looking at an old version of the PDF. Sorry.

could you mark this issue as closed?
