### ISSUE TITLE
is there a reason you used align* instead of the writtenletter env?

### ISSUE THREAD

**Issue by entorb** [rrthomas/hpmor#28]
Is there a reason you used align* instead of the writtenNote env? (at my ebook conversion i struggled a bit with those blocks)

https://github.com/rjl20/hpmor/blob/4670b0572c567608fc5702d109ce4afdf112d49e/chapters/hpmor-chapter-013.tex#L111

**Comment by rrthomas** [comment]
I think this predates my involvement in the project, but clearly there's a different look: `writtenNote` is handwritten, whereas the `align*` blocks are magically written, and often strictly aligned in a table, as the examples you gave.

Very happy to accept a PR that implements an easier-to-convert syntax if you can retain the look.

**Comment by entorb** [comment]
ok. For the ebook I kept it simple, treating them the same and removing the table structure.

**Comment by rrthomas** [comment]
Is it OK if I turn this into an issue to fix the formatting in the ePUB? Not urgent, of course, just nice-to-have some time in future.

**Comment by entorb** [comment]
Now that the font of the `writtenNote` have been changed (I like it a lot!) I think we should use the same font (and latex env) for the magical notes in chapter 13. Compare Page 149 (new) and 151 (old).

**Comment by rrthomas** [comment]
My rationale for having a different look for the two types of note (hand-written versus magically-written) remains, although I would indeed prefer a different font for the magical notes from that used, something less "printed".

**Comment by entorb** [comment]
Could we agree upon this wishlist:
Having a certain custom env (other than align*) for the "magical notes" and using some nice looking font?
(not that I know much fonts...) ?

**Comment by rrthomas** [comment]
> Could we agree upon this wishlist: Having a certain custom env (other than align*) for the "magical notes" and using some nice looking font?

I agree.

**Comment by entorb** [comment]
In 9675aa8f1ba4875314c87a1049ff7ff7bf8d271c I converted them to the writtenNote and tabular envs.
