### ISSUE TITLE
chapter 109, missing character -

### ISSUE THREAD

**Issue by yeKcim** [rrthomas/hpmor#48]
Parseltongue font doesn’t have "-" character. That's a problem in chapter 109: "an intent—who knowss?"

I’ve just add it in my fork (https://github.com/yeKcim/hpmor/commit/95c41b3639772b2d5813fdb6431811252ac671ed).

Is there a way to git pull this commit in your repository easiest than: git checkout my english branch, git add, git commit, git push, pull request?

**Comment by rrthomas** [comment]
Good catch! Check out your English branch, then use `git cherry-pick`.

**Comment by rrthomas** [comment]
Did you mean to make a PR for this?

**Comment by yeKcim** [comment]
yes in few days/weeks, a lot of work actually.

I’ve done a lot of changes on my french branch, I’ll have to talk about it with you (what you need or not, all in one PR or multiple ones…). On my branch: I changed some fonts, I’ve modified epub script converter to use pandoc (simpliest script and font embedded),…

![f974f4ff9e80662b](https://user-images.githubusercontent.com/10558744/163870645-45501362-13df-451a-ac32-61568b494a45.jpg)

![508cdd4a1ce1d0d2](https://user-images.githubusercontent.com/10558744/163870619-e88de1f0-2437-414c-a82b-3c03219991de.jpg)
 
![canvas](https://user-images.githubusercontent.com/10558744/163870626-3f0b5ada-eaee-4280-85f2-1bcfb6ed3ef8.png)

![canvasb](https://user-images.githubusercontent.com/10558744/163870632-7adc52c2-72e7-4ca5-8268-16f7d0c2fa3d.png)

**Comment by rrthomas** [comment]
I like the look! Also, I see the problem with Parsel that you have to not double silent "s" in French.

**Comment by entorb** [comment]
Wow, nice fonts, I really like them! Also your title page image looks great. I vote for adopting those.

Interesting that you found a way to use pandoc to generate a proper ebook. I gave up after having quite some issues in trying to make it load my custom css. So I decided to manually convert the tex to simple html...

**Comment by rrthomas** [comment]
I agree with @entorb, I like them; yes, please!
