### ISSUE TITLE
Please add @entorb as collaborator

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/hpmor#65]
Hi @rjl20, please could you invite @entorb to be a collaborator? As well as the German translation and ePub conversion he's doing a lot of good work on the general presentation and it's got to the point where it seems a needless roadblock for me to have to review everything he's doing.

At the same time, he points out it might also be useful to grant me the ability to administer the repo, simply to increase the bus factor. I would be quite happy to have that responsibility if you think it's appropriate.

**Comment by rjl20** [comment]
I've invited @entorb as a collaborator, but I can't find a way to add an administrator. It looks like I can transfer ownership to you, though. Want me to give that a try?

**Comment by rrthomas** [comment]
Thanks! I'd be happy to own the repo if that suits you.

**Comment by rjl20** [comment]
Ah, it's telling me "rrthomas/hpmor already exists" -- I think I can't transfer it to you while you have a repo with the same name. Should I rename mine, or do you want to rename yours?

**Comment by rrthomas** [comment]
Sorry, I've deleted my repo now, so you should be able to transfer yours.

**Comment by rjl20** [comment]
Ok, transfer in progress!

**Comment by rjl20** [comment]
It's all yours! Targets will probably have to be updated to /rrthomas/hpmor instead of /rjl20/hpmor.

**Comment by rrthomas** [comment]
Thanks @rjl20; have you/could you possibly update links from hpmor.com?

**Comment by rrthomas** [comment]
I've now updated the links in the repo.

**Comment by entorb** [comment]
Thanks a lot!

**Comment by rjl20** [comment]
I've changed the link to the latest release on the front page of hpmor.com; if there are other links to the old URL, let me know what page(s) they're on, and I'll get them as well.

**Comment by rrthomas** [comment]
Thanks, @rjl20, will do!
