### ISSUE TITLE
font used for part titlepages: could we make the "-" thinner?

### ISSUE THREAD

**Issue by entorb** [rrthomas/hpmor#68]
The "-" is too prominent. See for example this screenshot below, taken from the FR version Is anyone able to modify the font sligthly?

![image](https://user-images.githubusercontent.com/59419684/167188070-d10aa0c2-75e4-46ee-871b-0b4c2e5adcc4.png)

**Comment by yeKcim** [comment]
https://github.com/yeKcim/hpmor/commit/b25a206bca5c790a65a14e0840ef859e06979992
![Capture d’écran du 2022-05-27 22-53-08](https://user-images.githubusercontent.com/10558744/170788773-5378abcd-4443-4d27-89e6-cf3b93e339f6.png)

**Comment by entorb** [comment]
very nice!
