### ISSUE TITLE
nested emphs broken

### ISSUE THREAD

**Issue by entorb** [rrthomas/hpmor#79]
Test:
`\emph{emph1 emph1 \emph{emph2 \emph{emph3} emph2} emph1}`
Expectation:
_emph1 emph1_ emph2 _emph3_ emph2 _emph1_

Restult:
_emph1 emph1 emph2 emph3 emph2 emph1_

**Comment by rrthomas** [comment]
Oh dear, I wonder if this is why they weren't nested before.

**Comment by rrthomas** [comment]
OK, I can reproduce this.

**Comment by rrthomas** [comment]
I have narrowed down the cause to the font commands: if I comment out the `\setmainfont` command in `hp-format.tex`, then nested `\emph` works as expected. Still not sure *why* this should be, though…will continue to investigate.

**Comment by rrthomas** [comment]
Aha: https://tex.stackexchange.com/questions/178815/alegreya-prevents-nested-emph-commands-to-behave-as-expected

**Comment by rrthomas** [comment]
The hack on Stack Exchange didn't work, but updating the fonts did!

**Comment by entorb** [comment]
Thank you very much!
