### ISSUE TITLE
Collection of minor issues with the E-Book translation

### ISSUE THREAD

**Issue by fefrei** [rrthomas/hpmor#82]
Here's a set of minor issues I noticed with the E-Book:

- [x] Chapter 17:
    
      And if Paper-2 said 997$\times$997, Harry would leave Paper-1 blank.

    The parser translates `\times` to `×`, but leaves the `$` in.

- [x] Chapter 19:
 
      You will not be hurt and neither will I\@.

    The parser translates the `\@` into a space.

- [ ] Chapter 21:

      \begin{enumerate}[A.]{

    The e-book uses `1.`, `2.` etc. for numbering, which would be fine… but the text after the list talks about items `A` through `D`.

- [ ] Chapter 27:

      Mr~Carl Sloper

    With the way the Kindle renders it, when making the lines justified, the space protected space isn't stretched, which looks weird. I don't know whether this is a Kindle weirdness or the `MOBI` file could represent this better.

- [x] Chapter 58:

      we were to rescue a woman, you and I\@. You tried to slay the protector man

    Somehow, in the E-Book, this reads as _we were to rescue a woman, you and I\&nbsp;. You tried to slay the protector man_.

- [ ] Chapter 78:

      the most powerful wizard in the world \&c

    In the E-Book, this is typeset as „world &c.“

- [ ] Chapter 86:

      the sum over all possible excuses would be more than $.01$

      $2 + 2 = $…

    These _$_ signs do make it into the E-Book.

All these were found in the MOBI version, downloaded about a month ago – sorry about the noise if they have been fixed in the meantime :-)

**Comment by entorb** [comment]
Hi @fefrei, thank you  very much for the valuable feedback! I just finished the creation of a [German edition](https://github.com/entorb/hpmor-de/releases/tag/WorkInProgress), where I used a different set of tools for ebook creation. Now I plan to add this toolset to this repo as well. Unfortunately this will take some time, so for the moment I would prefer to keep this issue open until I fix in one way, or another...

**Comment by entorb** [comment]
Hi @fefrei
finally I found the time to rewrite the e-book generation. The remainder should hopefully be fixed by https://github.com/rrthomas/hpmor/pull/118

**Comment by fefrei** [comment]
Thank you!

It looks like `we were to rescue a woman, you and I\@. You tried to slay the protector man` is better now, but there's still an extra space left before the full stop.

Also, `$.01$` still seems to contain the dollar marks.

Apart from this, no more complaints. Thanks, again, for your work to make this masterpiece easily accessible on e-book readers!

**Comment by entorb** [comment]
Sorry, my reply was misleading, the PR is not merged yet...

**Comment by fefrei** [comment]
That explains that. Sorry 🙈

**Comment by entorb** [comment]
please check the new file at
https://github.com/rrthomas/hpmor/releases/WorkInProgress/

**Comment by entorb** [comment]
The new version of the file was missing in yesterday's released, now added, looks fine to me.

**Comment by fefrei** [comment]
All looking good now – thank you ❤️
